215 - feat: discord integration - part 1
thenewboston-developers/thenewboston-Backend pull request #217
Opened 2024-08-02 23:35 UTC by MAbdurrehman1

Closes #215

2024-08-04 18:24 UTC, buckyroberts commented on thenewboston/discord/utils/bot.py
> +            user = await sync_to_async(User.objects.get)(id=1)
Need to fix this `(id=1)`

2024-08-05 14:02 UTC, dmugtasimov requested changes
Added comments. Maybe I should work on some of them myself. Two major issue I see:
1) Keep OpenAIClient since it is a good pattern to use (it encapsulates integration logic)
2) Add unittests for the changes made

2024-08-05 14:03 UTC, dmugtasimov commented
Also unitests are failing

2024-08-06 22:55 UTC, dmugtasimov approved these changes

2024-08-06 23:06 UTC, buckyroberts approved these changes

2024-08-07 14:39 UTC, merged